version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      aws-cdk:
        patterns:
          - "aws-cdk*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
