#!/usr/bin/env node
// Renders the shared navigation (header + dropdowns, mobile slide-out menu,
// footer link line) from scripts/nav-data.mjs into every page, between
// marker comments:
//
//   <!-- nav:header --> ... <!-- /nav:header -->
//   <!-- nav:menu -->   ... <!-- /nav:menu -->
//   <!-- nav:footer --> ... <!-- /nav:footer -->
//
// Usage:
//   node scripts/sync-nav.mjs           rewrite all pages in place
//   node scripts/sync-nav.mjs --check   fail (exit 1) if any page drifts
//
// `npm run check:site` runs --check, so CI catches hand-edited nav blocks.
// aria-current="page" is stamped per page (each page knows its own path).

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { NAV, FOOTER_LINKS } from './nav-data.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', 'website');
const CHECK = process.argv.includes('--check');

const GEN_NOTE = 'generated by scripts/sync-nav.mjs; edit scripts/nav-data.mjs, then `npm run sync:nav`';

const LOGO_SVG = '<svg viewBox="0 0 264 350" fill="currentColor" aria-hidden="true"><defs><mask id="hdr-kh"><rect width="264" height="350" fill="white"/><circle cx="132" cy="190" r="29" fill="black"/><path d="M119 204 L104 282 Q102 292 112 292 L152 292 Q162 292 160 282 L145 204 Z" fill="black"/></mask></defs><path d="M8 0 L47 0 Q55 0 55 8 L55 54 L104 54 L104 8 Q104 0 112 0 L151 0 Q159 0 159 8 L159 54 L208 54 L208 8 Q208 0 216 0 L255 0 Q263 0 263 8 L263 76 Q263 86 254 90 L240 96 L23 96 L9 90 Q0 86 0 76 L0 8 Q0 0 8 0 Z"/><path mask="url(#hdr-kh)" d="M31 112 Q31 108 35 108 L229 108 Q233 108 233 112 L257 330 Q258 344 245 344 L19 344 Q6 344 7 330 Z"/></svg>';

// ── renderers ──────────────────────────────────────────────────────────────

function isCurrent(href, currentPath) {
  if (!currentPath || !href || href.startsWith('http')) return false;
  const norm = (p) => (p !== '/' && p.endsWith('/') ? p.slice(0, -1) : p);
  return norm(href) === norm(currentPath);
}

function link(item, currentPath, cls) {
  const attrs = [
    cls ? `class="${cls}"` : '',
    `href="${item.href}"`,
    isCurrent(item.href, currentPath) ? 'aria-current="page"' : '',
    item.external ? 'target="_blank" rel="noopener noreferrer"' : '',
  ].filter(Boolean).join(' ');
  return `<a ${attrs}>${item.label}</a>`;
}

function renderHeader(currentPath) {
  const groups = NAV.map((item) => {
    if (!item.children) return `    ${link(item, currentPath)}`;
    const parent = item.href
      ? `      <a class="nav-parent" ${isCurrent(item.href, currentPath) ? 'aria-current="page" ' : ''}href="${item.href}" aria-haspopup="true">${item.label}</a>`
      : `      <button type="button" class="nav-parent" aria-haspopup="true" aria-expanded="false">${item.label}</button>`;
    const children = item.children.map((c) => `        ${link(c, currentPath)}`).join('\n');
    return [
      '    <div class="nav-group">',
      parent,
      '      <div class="nav-drop">',
      children,
      '      </div>',
      '    </div>',
    ].join('\n');
  }).join('\n');

  return [
    '<header>',
    '  <a href="/" class="header-logo">',
    `    ${LOGO_SVG}`,
    '    <span>VETTID</span>',
    '  </a>',
    '  <nav class="desktop-nav">',
    groups,
    '  </nav>',
    '  <span class="coming-soon-chip">Coming Soon</span>',
    '  <button class="nav-toggle" aria-label="Toggle menu" aria-expanded="false">',
    '    <span></span><span></span><span></span>',
    '  </button>',
    '</header>',
  ].join('\n');
}

function renderMenu(currentPath) {
  const items = [`  <a ${isCurrent('/', currentPath) ? 'aria-current="page" ' : ''}href="/">Home</a>`];
  for (const item of NAV) {
    if (!item.children) {
      items.push(`  ${link(item, currentPath)}`);
      continue;
    }
    items.push(`  <span class="nav-menu-group">${item.label}</span>`);
    for (const c of item.children) items.push(`  ${link(c, currentPath, 'nav-menu-sub')}`);
  }
  return [
    '<div class="nav-menu" id="navMenu">',
    ...items,
    '</div>',
    '<div class="nav-overlay"></div>',
  ].join('\n');
}

function renderFooterNav() {
  const links = FOOTER_LINKS.map((l) => link(l, null)).join(' &middot; ');
  return `  <p class="footer-nav">${links}</p>`;
}

// ── stamping ───────────────────────────────────────────────────────────────

function stamp(src, name, body) {
  const re = new RegExp(`(<!-- nav:${name}[^>]*-->)[\\s\\S]*?(<!-- /nav:${name} -->)`);
  if (!re.test(src)) return null;
  return src.replace(re, `<!-- nav:${name} — ${GEN_NOTE} -->\n${body}\n<!-- /nav:${name} -->`);
}

function pagePath(file) {
  // website/why/index.html -> /why ; website/index.html -> / ; 404.html -> null
  const rel = '/' + file.slice(ROOT.length + 1).split(sep).join('/');
  if (rel === '/index.html') return '/';
  if (rel.endsWith('/index.html')) return rel.slice(0, -'/index.html'.length);
  return null;
}

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const errors = [];
let changed = 0;

for (const file of walk(ROOT).filter((p) => p.endsWith('.html'))) {
  const rel = file.slice(ROOT.length + 1);
  const src = readFileSync(file, 'utf8');
  // Every page with chrome participates; a page with neither markers nor a
  // <header> is a fragment and is left alone.
  if (!src.includes('<!-- nav:') && !src.includes('<header')) continue;

  const current = pagePath(file);
  let out = src;
  for (const [name, body] of [
    ['header', renderHeader(current)],
    ['menu', renderMenu(current)],
    ['footer', renderFooterNav()],
  ]) {
    const stamped = stamp(out, name, body);
    if (stamped === null) {
      errors.push(`${rel}: missing <!-- nav:${name} --> markers`);
      continue;
    }
    out = stamped;
  }

  if (out !== src) {
    if (CHECK) {
      errors.push(`${rel}: nav blocks out of sync (run \`npm run sync:nav\`)`);
    } else {
      writeFileSync(file, out);
      changed++;
    }
  }
}

if (errors.length) {
  console.error(`sync-nav ${CHECK ? 'check ' : ''}FAILED (${errors.length}):`);
  for (const e of errors) console.error(`  ✗ ${e}`);
  process.exit(1);
}
console.log(CHECK ? 'sync-nav check OK — all pages in sync' : `sync-nav OK — ${changed} page(s) updated`);
